name = "zola-pkm"
description = "A minimal theme adapted from AdiDoks, built to turn Obsidian PKM in a simple zola site."
license = "MIT"
homepage = "https://github.com/ppeetteerrs/zola-pkm"
min_version = "0.15.2"
demo = "https://peteryuen.netlify.app/"

[extra]

[author]
name = "Peter Yuen"
homepage = "https://github.com/ppeetteerrs/zola-pkm"

[original]
author =  "Aaran Xu"
homepage = "https://github.com/aaranxu"
repo = "https://github.com/aaranxu"
